### PR TITLE
Gallery website

### LINKED ISSUE #1: Create Gallery website
Automatically build the galleries, using MKDocs

### PR DESCRIPTION
**Pull request by diocas**
Closes #1 
Automatic build and deployment based on MkDocs. Available in https://swan-gallery.web.cern.ch/
@etejedor Please check the website and tell me if something should be changed.

Missing:
- [x] Fix fcc gallery
    - This gallery repo changed and is no longer up to date. @omazapa can you check with them what content should be published in SWAN and where it lives?
- [x] Fix lhc-sm gallery
    - This gallery repo changed and is no longer up to date. @prasanthkothuri can you check with them what content should be published in SWAN and where it lives?
- [x] Allow this website in "open with swan" (swan-cern/jupyter-extensions#43)

Eventually we also need to create a Lab extension and replace the nbextension to just open the website (#3).

### CODE REVIEW

**Comment by etejedor** [comment]
@diocas looks very good!

A few comments:
- In the main page, the second bullet "Jupyter notebook interface..." should start with a verb like the others.

- CERNBOX should be spelled CERNBox, right (not all in uppercase)?

- Perhaps this bullet: "Access experiments' and user data in the CERN cloud" I would replace it by: "Access LCG and experiments' software on CVMFS". Links: https://cernvm.cern.ch/portal/filesystem (CVMFS) and LCG software: http://lcginfo.cern.ch/

- When opening the static rendering of a notebook, it seems that in some code cells there is little space between the title and the rest of the text. e.g.:
https://swan-gallery.web.cern.ch/notebooks/accelerator_complex/examples/LHC_Page1.html

- When I try to "Open in SWAN" any notebook, from the static rendering page, I get redirected to SWAN but I end up having an error:
```
Error downloading Project: The URL of the project is not a github, CERN gitlab, CERNBox shared link nor root.cern.ch URL. It is not a path on EOS either.
```

**Comment by kruezbergbier** [comment]
Fell into black space

**Comment by kruezbergbier** [comment]
print "Exploration of the variables' tree"
db.tree.LHC.Beam_Instrumentation.Beam_Position.DOROS_BPMs.IP1.LHC_BPM_1L1_B1_DOROS_ACQUISITION_STATUS
Exploration of the variables' tree
Out[6]:
u'LHC.BPM.1L1.B1.DOROS:ACQUISITION_STATUS'

**Comment by diocas** [comment]
Merging this PR. The FCC gallery was removed and the LHC SM will be updated in a following PR.

**Pull request merged**
